import { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { envConfig } from '~/config'
import './globals.css'

console.log(envConfig)

const inter = Inter({
  subsets: ['vietnamese'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  )
}
